openapi: 3.0.0
info:
  title: Jobs-API
  contact: {}
  version: '1.0'
servers:
- url: https://job-api-s1sc.onrender.com/api/v1
  variables: {}
paths:
  /jobs:
    get:
      tags:
      - Job
      summary: Get All Jobs
      operationId: GetAllJobs
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security:
      - bearer: []
    post:
      tags:
      - Job
      summary: Create Job
      operationId: CreateJob
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/CreateJobRequest'
              - example:
                  company: company
                  position: position
            example:
              company: company
              position: position
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /jobs/{id}:
    get: 
      tags:
      - Job
      summary: Get Single Job
      parameters: 
      - in: path
        name: id
        description: jobId
        required: true
        schema: 
          type: string
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security:
      - bearer: []
    patch:
        tags:
        - Job
        summary: Update job
        operationId: Updatejob
        parameters:
        - in: path
          name: id
          description: jobId
          required: true
          schema:
            type: string
        requestBody:
          description: ''
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/UpdatejobRequest'
                - example:
                    company: company
                    position: position
                    status: pending
              example:
                company: company
                position: position
                status: pending
          required: true
        responses:
          '200':
            description: ''
            headers: {}
        deprecated: false
        security:
        - bearer: []
    delete:
      tags:
      - Job
      summary: Delete Job
      operationId: DeleteJob
      parameters:
      - in: path
        name: id
        description: job id
        required: true
        explode: true
        schema:
          type: string
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security:
      - bearer: []
  /auth/login:
    post:
      tags:
      - Auth
      summary: Login
      operationId: Login
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/LoginRequest'
              - example:
                  email: deployed2render@gmail.com
                  password: password123
            example:
              email: deployed2render@gmail.com
              password: password123
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security: []
  /auth/register:
    post:
      tags:
      - Auth
      summary: Register
      operationId: Register
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/RegisterRequest'
              - example:
                  name: name
                  email: email
                  password: password
            example:
              name: name
              email: email
              password: password
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security: []
components:
  schemas:
    CreateJobRequest:
      title: CreateJobRequest
      required:
      - company
      - position
      type: object
      properties:
        company:
          type: string
        position:
          type: string
      example:
        company: company
        position: position
    LoginRequest:
      title: LoginRequest
      required:
      - email
      - password
      type: object
      properties:
        email:
          type: string
        password:
          type: string
      example:
        email: deployed2render@gmail.com
        password: password123
    RegisterRequest:
      title: RegisterRequest
      required:
      - name
      - email
      - password
      type: object
      properties:
        name:
          type: string
        email:
          type: string
        password:
          type: string
      example:
        name: name
        email: email
        password: password
    UpdatejobRequest:
      title: UpdatejobRequest
      required:
      - company
      - position
      - status
      type: object
      properties:
        company:
          type: string
        position:
          type: string
        status:
          type: string
      example:
        company: company
        position: position
        status: pending
  securitySchemes:
    bearer:
      type: http
      scheme: bearer
security: []
tags:
- name: Job
  description: ''
- name: Auth
  description: ''